import test from "node:test";
import assert from "node:assert/strict";
import { directoryHasNonPhotoFile, directoryHasProgram, isBelowDriveFirstLevel, isBundledAssetName, isPhotoRelatedFile, isSoftwareBoundary } from "../src/skip.js";

test("跳过系统和软件自带的目录，保留拍摄目录", () => {
  assert.equal(isSoftwareBoundary("C:\\Windows"), true);
  assert.equal(isSoftwareBoundary("C:\\Windows\\Web\\Wallpaper"), true);
  assert.equal(isSoftwareBoundary("C:\\Program Files\\Adobe"), true);
  assert.equal(isSoftwareBoundary("D:\\Adobe\\Adobe Photoshop 2020\\Required\\CEP\\extensions\\com.adobe.ccx.fnft\\images\\products"), true);
  assert.equal(isSoftwareBoundary("D:\\Photos\\2024\\DCIM"), false);
  assert.equal(isSoftwareBoundary("D:\\Program Files (x86)"), true);
  assert.equal(isSoftwareBoundary("C:\\Users\\me\\AppData"), true);
  assert.equal(isSoftwareBoundary("C:\\Users\\me\\AppData\\Local\\Temp\\photo"), false);
  assert.equal(isSoftwareBoundary("D:\\Steam\\steamapps"), true);
  assert.equal(isSoftwareBoundary("C:\\Users\\Public\\Pictures\\Sample Pictures"), true);
  assert.equal(isSoftwareBoundary("D:\\Photos\\2024\\DCIM"), false);
  assert.equal(isSoftwareBoundary("C:\\Users\\me\\Documents\\WeChat Files"), false);
  assert.equal(isSoftwareBoundary("D:\\Photos\\node_modules"), true);
  assert.equal(isSoftwareBoundary("D:\\工具\\美图\\icons"), true);
  assert.equal(isSoftwareBoundary("D:\\工具\\美图\\缓存"), true);
  assert.equal(isSoftwareBoundary("D:\\Photos\\2024\\表情"), true);
  assert.equal(isSoftwareBoundary("D:\\Photos\\2024"), false);
  assert.equal(isBundledAssetName("images"), true);
  assert.equal(isBundledAssetName("DCIM"), false);
  assert.equal(directoryHasProgram(["readme.txt", "app.exe"]), true);
  assert.equal(directoryHasProgram(["IMG_0001.jpg", "IMG_0002.HEIC"]), false);
  assert.equal(isPhotoRelatedFile("IMG_0001.CR2"), true);
  assert.equal(isPhotoRelatedFile("clip.mp4"), true);
  assert.equal(isPhotoRelatedFile("IMG_0001.xmp"), true);
  assert.equal(isPhotoRelatedFile("desktop.ini"), true);
  assert.equal(isPhotoRelatedFile("Thumbs.db"), true);
  assert.equal(isPhotoRelatedFile("notes.txt"), false);
  assert.equal(isPhotoRelatedFile("index.html"), false);
  assert.equal(directoryHasNonPhotoFile(["IMG_0001.jpg", "desktop.ini"]), false);
  assert.equal(directoryHasNonPhotoFile(["IMG_0001.jpg", "notes.txt"]), true);
  assert.equal(isBelowDriveFirstLevel("D:\\"), false);
  assert.equal(isBelowDriveFirstLevel("D:\\xxx"), false);
  assert.equal(isBelowDriveFirstLevel("D:\\xxx\\XXX"), true);
  assert.equal(isBelowDriveFirstLevel("D:\\xxx\\XXX\\相册"), true);
});
